<?php
/* password_confirm.module,v 1.0 2008/04/28 14:18:44 StickyTouch.com Exp $ */

/**
 * @file
 * This module adds a level of security to the change password form by forcing users to enter their current password.
 */


function _password_confirm_password_validate( &$form_field, $form_id, &$form_values ){
  // drupal_set_message('_password_confirm_password_validate; $form_values: '. print_r($form_values, TRUE) );
  if( !empty($form_values['pass']['pass1'] ) ){
   $verify = user_load( array( 'name'=>$form_values['pass']['pass3name'], 'pass'=>$form_values['pass']['pass3'] ) );
   if( !$verify ) {
    form_set_error('name', t('Sorry, unable to verify current password.  Please try again.') );
    watchdog('user', t('Password change attempt failed for %user.', array('%user' => $form_values['name'])));
    }
   }
}

function password_confirm_user($op, &$edit, &$account, $category = NULL) {
  if( $op == 'form' && $category == 'account' ) {
   global $user;

   /* Don't show the forum if admin is editing another user */
   if( $user->uid == $account->uid ){
    /* The user name is not always included in the form (depends on 
     * change username permissions) so we include is separately here
     */
    $form['account']['pass']['pass3name'] = array(
      '#type' => 'hidden',
      '#default_value' => $user->name
      );
    
    $form['account']['pass']['pass3'] = array(
      '#type' => 'password',
      '#title' => t('Current Password'),
      '#description' => t('Only required if changing your password below.'),
      '#validate' => array('_password_confirm_password_validate' => array($edit['form_id'], $edit))
      );
    return $form;
    }
   }
}

